name: Build
permissions: write-all
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version to release'
        required: false
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/issues.yml'

jobs:
  build:
    runs-on: windows-latest
    name: Build windows-x64-7z

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Determine and Update Version
        shell: bash
        run: |
          GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
          VERSION=$(jq -r '.version' package.json)

          if [ "${{ github.event.inputs.version }}" == "" ]; then
            BASE_VERSION=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
            VERSION_PREFIX=${VERSION_PREFIX:-beta}
            RELEASE_VERSION="${BASE_VERSION}-${VERSION_PREFIX}-${GIT_COMMIT_HASH}"
          else
            INPUT_VERSION="${{ github.event.inputs.version }}"
            CLEAN_VERSION=$(echo "$INPUT_VERSION" | sed 's/^v//')
            if [[ ! "$CLEAN_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Invalid version format: $INPUT_VERSION"
              exit 1
            fi
            RELEASE_VERSION="$CLEAN_VERSION"
          fi

          jq --arg version "$RELEASE_VERSION" '.version = $version' package.json > tmp.json && mv tmp.json package.json

      - name: Install Dependencies and Prepare
        shell: bash
        run: |
          SKIP_PREPARE=1 pnpm install
          pnpm prepare --x64

      - name: Build
        shell: bash
        run: pnpm build:win 7z --x64

      - name: Add Portable Flag
        shell: pwsh
        run: |
          New-Item -Path "PORTABLE" -ItemType File
          Get-ChildItem dist/*portable.7z | ForEach-Object {
            7z a $_.FullName PORTABLE
          }

      - name: Create Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git log -1 --pretty=format:"%s%n%b" > changelog.md

      - name: Generate latest.yml
        shell: bash
        run: SKIP_CHANGELOG=1 pnpm updater

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-7z
          path: |
            dist/xuanlian-vpn*
            !dist/xuanlian-vpn*.blockmap*
            latest.yml
            changelog.md

  pre-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin/
          merge-multiple: true

      - name: Delete current release assets
        uses: 8Mi-Tech/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: pre-release
          deleteOnlyFromDrafts: false

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Prerelease
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pre-release
          body_path: bin/changelog.md
          files: |
            bin/latest.yml
            bin/dist/*
          prerelease: true

  release:
    if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && github.event.inputs.version != '')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          fetch-tags: 'true'

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin/
          merge-multiple: true

      - name: Delete Current
        uses: 8Mi-Tech/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version != '' && github.event.inputs.version || github.ref }}
          deleteOnlyFromDrafts: false

      - name: Publish Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version != '' && github.event.inputs.version || github.ref }}
          body_path: bin/changelog.md
          files: |
            bin/latest.yml
            bin/dist/*
